Controllers/GamesController.cs
namespace GameZone.Controllers
{

    [Authorize(Roles = "Admin")]
    public class GamesController : Controller
    {
		private readonly ApplicationDbContext _context;
		private readonly ICategoriesService _CategoriesService;
		private readonly IDevicesService _DevicesService;
		private readonly IGamesService _gamesService;

		public GamesController(ApplicationDbContext context, ICategoriesService CategoriesService, 
            IDevicesService DevicesService, IGamesService gamesService)
        {
            _context = context;
			_CategoriesService = CategoriesService;
			_DevicesService = DevicesService;
            _gamesService = gamesService;
		}

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_gamesService.GetAll());
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var game = _gamesService.GetById(id);
            if (game is null)
                return NotFound();
            return View(game);
        }

        [HttpGet]
        public IActionResult Create()
        {
            CreateGameFormViewModel moodel = new()
            {
                Categories = _CategoriesService.GetSelectList(),

				Devices = _DevicesService.GetSelectList(),
			};

            return View(moodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGameFormViewModel model)
        {
            if (!ModelState.IsValid) // server side validation
            {
                model.Categories = _CategoriesService.GetSelectList();

                model.Devices = _DevicesService.GetSelectList();

				return View(model);
            }

            await _gamesService.Create(model);
            return RedirectToAction(nameof(Index));
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
            var game = _gamesService.GetById(id);
            if (game is null)
                return NotFound();

            EditGameFormViewModel viewModel = new()
            {
                Id = id,
                Name = game.Name,
                Description = game.Description,
                CategoryId = game.CategoryId,
                SelectedDevices = game.Devices.Select(d => d.DeviceId).ToList(),
                Categories = _CategoriesService.GetSelectList(),
                Devices = _DevicesService.GetSelectList(),
                currentCover = game.Cover,
            };

            return View(viewModel);
        }

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(EditGameFormViewModel model)
		{
			if (!ModelState.IsValid) // server side validation
			{
				model.Categories = _CategoriesService.GetSelectList();

				model.Devices = _DevicesService.GetSelectList();

				return View(model);
			}

			var game = await _gamesService.Edit(model);

            if (game is null)
                return BadRequest();

			return RedirectToAction(nameof(Index));
		}

		[HttpDelete]
		public IActionResult Delete(int id)
		{
            var isDeleted = _gamesService.Delete(id);

            if (isDeleted) return Ok();

            return BadRequest();
		}
	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GameZone | @ViewData["Title"]</title>
    @* Bootstrap File *@
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    @* Icon Link *@
    <link rel ="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    @* Fonts *@
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Chakra+Petch:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap">
    @* Select2 css *@
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css" />
    @* Alert2 css *@
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    @* CSS File *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/GameZone.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between align-items-center">
                    <div class="d-flex justify-content-center align-items-center">
                        <a class="navbar-brand flex-grow-1 fw-bolder fs-4" style="color:#6520e0" asp-controller="Home" asp-action="Index">GameZone</a>
                        @if(User.IsInRole("Admin"))
                        {
                            <a class="navbar-brand fw-bolder" style="color:#1a0b35" asp-controller="Games" asp-action="Index">Games</a>
                            <a class="navbar-brand fw-bolder" style="color:#1a0b35" asp-controller="account" asp-action="addadmin">Add Admin</a>
                        }
                    </div>
                </div>
               <div>
                    <div class="d-flex justify-content-center align-items-center">
                        @if(User.Identity.IsAuthenticated == true)
                        {
                            <a class="navbar-brand fw-bolder" style="color:#1a0b35" asp-controller="home" asp-action="index">Welcome @User.Identity.Name</a>
                            <a class="navbar-brand fw-bolder" style="color:#1a0b35" asp-controller="account" asp-action="logout">Logout</a>
                        }
                        else
                        {
                            <a class="navbar-brand fw-bolder" style="color:#1a0b35" asp-controller="account" asp-action="register">Register</a>
                            <a class="navbar-brand fw-bolder" style="color:#1a0b35" asp-controller="account" asp-action="login">Login</a>
                        }
                    </div>
               </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GameZone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/select2/js/select2.min.js"></script>
	<script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>